#!/usr/bin/env bash
#install nginx on ubuntu@35.231.52.206	
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
