#!/usr/bin/env bash
#install nginx on ubuntu@35.231.52.206	
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
