#!/usr/bin/env bash
#install nginx on ubuntu@35.231.52.206	
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
