#!/usr/bin/env bash
# configurating a load balancer
sudo apt-get -y update
sudo apt-get install -y haproxy=1.6.\*
sudo sed -i '$ a\\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1291-web-01 35.231.52.206:80\n\tserver 1291-web-02 54.226.104.83' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
