#!/usr/bin/env bash
# This script checks if the file exists
FILE=./holbertonschool
if [ -f "$FILE" ]
then
    echo "holbertonschool file exists"
    if [ -s "$FILE" ] 
    then
    	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool is empty"
    fi
    echo "holbertonschool is a regular file"
fi  
if [ -d "$FILE" ]
then
    echo "holbertonschool file exists"
    if [ -s "$FILE" ] 
    then
    	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool is empty"
    fi
fi    
if [ ! -f "$FILE" -a ! -d "$FILE" ]
then
    echo "holbertonschool file does not exist"
fi
